"""Parity gate: the Python offline engine against the live TypeScript engine.

designesy_score falls back to a Python port of the scoring engine when the
live API is unreachable. Nothing compared the two until this file, and the
port had drifted far enough that its offline scores disagreed with the site's
on the same page.

HOW IT WORKS
packages/score/scripts/export-offline-golden.mjs runs the built TypeScript
engine (the same check code as the live route; source-drift.mjs keeps the two
identical) over the calibration corpus, the recorded parity page, edge inputs
and scope auto-detection cases, under both scopes, and writes every check
result to test/fixtures/offline-engine-golden.json. This file scores the same
inputs with the Python engine and requires the same status, item, category and
detail for every check the Python engine runs.

CI runs the exporter with --check, so the golden cannot fall behind the
TypeScript engine; a change there regenerates the golden, and this file then
fails until the port follows.

NO SILENT GAPS
Checks the Python engine does not run are listed, with a reason, in
designesy_mcp_server._OFFLINE_NOT_IMPLEMENTED. The ported list and that list
must together be exactly the live engine's check list, so a check added to the
live engine fails here until it is ported or listed.

WHAT THIS DOES NOT MEASURE
The browser probes for v02 and v21 (they need Chrome on 127.0.0.1:9222; the
parity runs score with browser_probes=False and both engines read MANUAL), the
network fetch itself (timeouts, redirects, candidate URLs), and the score: the
offline score is an unweighted pass rate over a subset and says so.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from unittest.mock import patch

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import designesy_mcp_server as mcp  # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
GOLDEN = HERE / "fixtures" / "offline-engine-golden.json"

with GOLDEN.open(encoding="utf-8") as _f:
    G = json.load(_f)

RECORDS: dict[str, dict] = G["records"]
FIELDS = ("status", "item", "category", "detail")
BROWSER_ONLY = {"v02", "v04", "v21"}


def _inputs(case: dict) -> tuple[str, str]:
    if "input_ref" in case:
        with (REPO / case["input_ref"]).open(encoding="utf-8") as f:
            page = json.load(f)
        return page["html"], page["css"]
    return case["html"], case["css"]


def _expected(key: str) -> dict:
    cid, status, _ = key.split(":")
    return {"id": cid, "status": status, **RECORDS[key]}


def _diff_run(case: dict, run: dict) -> list[str]:
    """Every way the Python engine's run differs from the TypeScript one."""
    html, css = _inputs(case)
    effective, raw_tokens, checks = mcp._offline_checks(html, css, run["subject"], run["scope"])
    problems = []
    if effective != run["effective_scope"]:
        problems.append(f"effective scope: python={effective!r} ts={run['effective_scope']!r}")
    if len(raw_tokens) != run["tokens_extracted"]:
        problems.append(f"tokens_extracted: python={len(raw_tokens)} ts={run['tokens_extracted']}")
    by_id = {c["id"]: c for c in checks}
    for key in run["checks"]:
        want = _expected(key)
        got = by_id.get(want["id"])
        if got is None:
            continue  # not ported: covered by test_every_live_check_is_ported_or_listed
        for field in FIELDS:
            if got[field] != want[field]:
                problems.append(f"{want['id']}.{field}: python={got[field]!r} ts={want[field]!r}")
    return problems


RUNS = [(case, i, run) for case in G["case_detail"] for i, run in enumerate(case["runs"])]


def _run_id(item) -> str:
    case, i, run = item
    return f"{case['name']}[{run['scope'] or 'auto'}#{i}]"


# ── The golden itself ─────────────────────────────────────────────────────────


class TestGolden:
    def test_is_generated_from_the_typescript_engine(self):
        assert "GENERATED by packages/score/scripts/export-offline-golden.mjs" in G["$comment"]
        assert G["cases"] == len(G["case_detail"])
        assert G["runs"] == len(RUNS)
        assert len(G["check_ids"]) == len(set(G["check_ids"])) == 44

    def test_every_run_lists_every_live_check_once_in_order(self):
        for case, _, run in RUNS:
            assert [k.split(":")[0] for k in run["checks"]] == G["check_ids"], case["name"]
            assert all(k in RECORDS for k in run["checks"]), case["name"]

    def test_parity_page_input_is_the_one_the_golden_was_made_from(self):
        # The page is read from packages/score rather than copied into the
        # golden, so a re-recorded page must come with a regenerated golden.
        (case,) = [c for c in G["case_detail"] if "input_ref" in c]
        html, css = _inputs(case)
        digest = hashlib.sha256((html + "\u0000" + css).encode("utf-8")).hexdigest()
        assert digest == case["input_sha256"]

    def test_covers_each_engine_1_1_0_change_in_both_directions(self):
        seen = defaultdict(set)
        for _, _, run in RUNS:
            for key in run["checks"]:
                rec = _expected(key)
                seen[(rec["id"], run["effective_scope"])].add((rec["status"], rec["detail"]))
        v05 = seen[("v05", "contract")] | seen[("v05", "universal")]
        assert any(s == "PASS" and d.startswith("motion is opt-in") for s, d in v05)
        assert any(s == "WARN" and "gates no motion" in d for s, d in v05)
        v27 = seen[("v27", "contract")] | seen[("v27", "universal")]
        assert {"SKIP", "WARN", "PASS", "FAIL"} <= {s for s, _ in v27}
        for cid in ("v14", "v18"):
            assert any(s == "SKIP" and "scope=universal" in d for s, d in seen[(cid, "universal")]), cid
            assert any(s == "WARN" for s, _ in seen[(cid, "contract")]), cid

    def test_reaches_more_than_one_verdict_for_every_ported_check(self):
        # A check the golden only ever sees in one state is compared, but not
        # tested: a port that hard-coded that state would pass. Only the three
        # browser-only checks are constant by design.
        statuses = defaultdict(set)
        for _, _, run in RUNS:
            for key in run["checks"]:
                cid, status, _ = key.split(":")
                statuses[cid].add(status)
        thin = [cid for cid in mcp.OFFLINE_CHECK_IDS if cid not in BROWSER_ONLY and len(statuses[cid]) < 2]
        assert thin == [], f"golden never moves these checks off one verdict: {thin}"
        assert all(statuses[cid] == {"MANUAL"} for cid in BROWSER_ONLY)


# ── Coverage: ported or listed, nothing silent ──────────────────────────────────


class TestCoverage:
    def test_every_live_check_is_ported_or_listed(self):
        live = G["check_ids"]
        ported = set(mcp.OFFLINE_CHECK_IDS)
        listed = set(mcp._OFFLINE_NOT_IMPLEMENTED)
        assert ported.isdisjoint(listed), sorted(ported & listed)
        assert ported | listed == set(live), {
            "in the live engine, neither ported nor listed": sorted(set(live) - ported - listed),
            "ported or listed, not in the live engine": sorted((ported | listed) - set(live)),
        }

    def test_ported_checks_keep_the_live_order(self):
        assert list(mcp.OFFLINE_CHECK_IDS) == [c for c in G["check_ids"] if c in set(mcp.OFFLINE_CHECK_IDS)]
        assert list(mcp._OFFLINE_NOT_IMPLEMENTED) == [c for c in G["check_ids"] if c in mcp._OFFLINE_NOT_IMPLEMENTED]

    def test_every_listed_check_carries_a_reason(self):
        for cid, reason in mcp._OFFLINE_NOT_IMPLEMENTED.items():
            assert len(reason) > 40, cid

    def test_the_engine_runs_exactly_the_ported_checks(self):
        _, _, checks = mcp._offline_checks("<html></html>", "")
        assert [c["id"] for c in checks] == list(mcp.OFFLINE_CHECK_IDS)

    def test_mirrored_versions_match_the_live_engine(self):
        assert mcp.OFFLINE_ENGINE_MIRRORS == G["engine_version"]
        assert mcp.OFFLINE_CONTRACT_VERSION == G["contract_version"]
        # Also against the live constant directly, so a version bump fails here
        # even before anyone regenerates the golden.
        src = (REPO / "apps/site/app/lib/check-definitions.ts").read_text(encoding="utf-8")
        live = re.search(r"export const ENGINE_VERSION = '(\d+\.\d+\.\d+)';", src).group(1)
        assert mcp.OFFLINE_ENGINE_MIRRORS == live

    def test_the_published_counts_are_the_engines(self):
        ported = len(mcp.OFFLINE_CHECK_IDS)
        total = ported + len(mcp._OFFLINE_NOT_IMPLEMENTED)
        phrase = f"{ported} of the {total} checks"
        assert phrase in mcp.TOOL_MAP["designesy_score"]["description"]
        assert phrase in (HERE.parent / "README.md").read_text(encoding="utf-8")


# ── Parity, run by run ─────────────────────────────────────────────────────────


@pytest.mark.parametrize("item", RUNS, ids=[_run_id(r) for r in RUNS])
def test_parity(item):
    case, _, run = item
    problems = _diff_run(case, run)
    assert problems == [], f"{case['name']} scope={run['scope']} subject={run['subject']}:\n  " + "\n  ".join(problems)


def test_the_comparison_catches_a_reverted_engine_1_1_0_change():
    # Negative control. If the comparison had no teeth (a wrong field, an
    # empty golden, a skipped branch), reverting a 1.1.0 change would still
    # pass. Each revert below must produce mismatches on the check it touches.
    def mismatched_ids() -> Counter:
        ids = Counter()
        for case, _, run in RUNS:
            for p in _diff_run(case, run):
                ids[p.split(".")[0]] += 1
        return ids

    with patch.object(mcp, "_opts_into_motion", lambda body: False):
        assert set(mismatched_ids()) == {"v05"}
    with patch.object(mcp, "_has_zoomable_field", lambda html: True):
        assert set(mismatched_ids()) == {"v27"}
    tier1 = [t for t in mcp._TIER2_ABSENCE_PATTERNS if t[0] not in ("v14", "v18")]
    with patch.object(mcp, "_TIER2_ABSENCE_PATTERNS", tier1):
        assert set(mismatched_ids()) == {"v14", "v18"}


# ── JavaScript semantics the port depends on ────────────────────────────────────


class TestJsSemantics:
    @pytest.mark.parametrize("x, want", [
        (13.0, "13"), (0.96, "0.96"), (1.5, "1.5"), (0.0, "0"), (-2.5, "-2.5"),
        (1e21, "1e+21"), (1e-7, "1e-7"), (0.000001, "0.000001"), (123456789012345680000.0, "123456789012345680000"),
        (math.nan, "NaN"), (math.inf, "Infinity"),
    ])
    def test_number_to_string(self, x, want):
        assert mcp._js_num(x) == want

    @pytest.mark.parametrize("x, places, want", [
        (0.125, 2, "0.13"), (2.5, 0, "3"), (1.005, 2, "1.00"), (4.5, 2, "4.50"),
        (21.0, 2, "21.00"), (-0.0, 2, "0.00"), (math.nan, 2, "NaN"),
    ])
    def test_to_fixed(self, x, places, want):
        assert mcp._js_fixed(x, places) == want

    @pytest.mark.parametrize("s, want", [("0.9.5", 0.9), ("1.", 1.0), (".96", 0.96), ("  12px", 12.0), ("1e3x", 1000.0)])
    def test_parse_float_prefix(self, s, want):
        assert mcp._js_float(s) == want

    @pytest.mark.parametrize("s", [".", "", "px", "-"])
    def test_parse_float_nan(self, s):
        assert math.isnan(mcp._js_float(s))

    @pytest.mark.parametrize("s, radix, want", [("5g", 16, 5.0), ("ff", 16, 255.0), ("-f", 16, -15.0), ("0x1", 16, 1.0), ("12", 10, 12.0)])
    def test_parse_int_prefix(self, s, radix, want):
        assert mcp._js_int(s, radix) == want

    @pytest.mark.parametrize("s, radix", [("g0", 16), ("0x", 16), ("", 10)])
    def test_parse_int_nan(self, s, radix):
        assert math.isnan(mcp._js_int(s, radix))

    def test_trim_strips_the_js_whitespace_set(self):
        assert mcp._js_trim("﻿ #fff  ") == "#fff"

    def test_regex_whitespace_case_and_end(self):
        assert mcp._js_re(r"transition\s*:\s*all", "i").search("transition: all")
        assert not mcp._js_re(r"transition", "i").search("transıtion")  # dotless i does not fold
        assert not mcp._js_re(r"\w").search("é")  # \w is ASCII in JS
        assert not mcp._js_re(r"^a$").search("a\n")  # $ is end of input
        assert not mcp._js_re(r"a.b").search("a\rb")  # . stops at \r in JS

    def test_regex_rejects_flags_it_cannot_reproduce(self):
        with pytest.raises(ValueError):
            mcp._js_re("a", "m")

    def test_pow_is_nan_not_complex(self):
        assert math.isnan(mcp._js_pow(-0.5, 2.4))


# ── What the offline result says about itself ───────────────────────────────────


GOOD = next(c for c in G["case_detail"] if c["name"] == "corpus/good-baseline")


class TestOfflineResult:
    def test_names_itself_offline_and_the_version_it_mirrors(self):
        r = mcp._offline_result("https://example.com/", GOOD["html"], GOOD["css"])
        assert r["engine"] == {
            "kind": "offline",
            "mirrors_engine_version": mcp.OFFLINE_ENGINE_MIRRORS,
            "checks_run": len(mcp.OFFLINE_CHECK_IDS),
            "checks_in_live_engine": len(G["check_ids"]),
            "not_run": list(mcp._OFFLINE_NOT_IMPLEMENTED),
        }
        assert r["note"].startswith("Offline engine, not the live one")
        assert f"mirror live engine {mcp.OFFLINE_ENGINE_MIRRORS}" in r["note"]
        assert "not the live engine's weighted score" in r["note"]
        assert r["contract_version"] == mcp.OFFLINE_CONTRACT_VERSION

    def test_scope_is_applied_and_reported(self):
        auto_ext = mcp._offline_result("https://example.com/", GOOD["html"], GOOD["css"])
        auto_own = mcp._offline_result("https://www.designesy.org/", GOOD["html"], GOOD["css"])
        forced = mcp._offline_result("https://example.com/", GOOD["html"], GOOD["css"], scope="contract")
        assert (auto_ext["scope"], auto_own["scope"], forced["scope"]) == ("universal", "contract", "contract")
        assert "scope (universal)" in auto_ext["note"]

    def test_summary_counts_add_up_and_manual_is_not_scored(self):
        r = mcp._offline_result("https://example.com/", GOOD["html"], GOOD["css"])
        s = r["summary"]
        assert s["total"] == len(r["checks"]) == len(mcp.OFFLINE_CHECK_IDS)
        assert s["pass"] + s["fail"] + s["warn"] + s["skip"] + s["manual"] == s["total"]
        assert s["manual"] == 3  # v02, v04, v21 without a browser
        scored = s["total"] - s["skip"] - s["manual"]
        assert s["score"] == round((s["pass"] + 0.5 * s["warn"]) / scored, 4)


class TestScoreLocalImpl:
    PAGE = (
        '<html><head><style>:root{--paper:#fff}</style>'
        '<link rel="stylesheet" href="/a.css">'
        '<link href="/ignored.css" rel="stylesheet">'
        '<link rel="stylesheet" href="https://cdn.example.com/b.css">'
        '<link rel="stylesheet" href="/a.css">'
        '</head><body><main><h1>x</h1></main></body></html>'
    )

    def _fake_fetch(self, calls):
        sheets = {
            "https://example.com/a.css": "a{color:red}",
            "https://cdn.example.com/b.css": "b{color:blue}",
        }

        def fetch(url, as_json=True):
            calls.append(url)
            if url == "https://example.com/":
                return self.PAGE
            if url in sheets:
                return sheets[url]
            raise AssertionError(f"unexpected fetch {url}")
        return fetch

    def test_assembles_css_as_the_live_route_does_and_never_calls_the_site(self):
        calls: list[str] = []
        seen = {}
        real = mcp._offline_result

        def capture(url, html, css, scope=None, browser_probes=False):
            seen["css"] = css
            return real(url, html, css, scope, browser_probes=False)

        with patch.object(mcp, "_fetch", self._fake_fetch(calls)), patch.object(mcp, "_offline_result", capture):
            r = mcp._score_local_impl("https://example.com/")
        # Inline first, then each distinct rel-before-href sheet once, in order.
        assert seen["css"] == ":root{--paper:#fff}\na{color:red}\nb{color:blue}"
        assert calls == ["https://example.com/", "https://example.com/a.css", "https://cdn.example.com/b.css"]
        assert not any(c.startswith(mcp.BASE_URL) for c in calls)
        assert r["scope"] == "universal"

    def test_passes_the_requested_scope(self):
        with patch.object(mcp, "_fetch", self._fake_fetch([])), patch.object(mcp, "_cdp_available", lambda: False):
            assert mcp._score_local_impl("https://example.com/", "contract")["scope"] == "contract"
            assert mcp._score_local_impl("https://example.com/")["scope"] == "universal"

    def test_without_a_browser_the_probes_read_manual(self):
        with patch.object(mcp, "_fetch", self._fake_fetch([])), patch.object(mcp, "_cdp_available", lambda: False):
            r = mcp._score_local_impl("https://example.com/")
        by_id = {c["id"]: c for c in r["checks"]}
        assert by_id["v02"]["status"] == by_id["v04"]["status"] == by_id["v21"]["status"] == "MANUAL"
