// /api/report/app — MCP App surface for the Designesy Report.
//
// Returns a self-contained HTML5 document (the MCP Apps `ui://` resource
// content, MIME `text/html;profile=mcp-app`) that renders an interactive
// design-intelligence dashboard for a given URL. Works two ways:
//
//   1. As an MCP App (SEP-1865, ext `io.modelcontextprotocol/ui`):
//      The MCP tool `designesy_report` declares `_meta.ui.resourceUri`
//      pointing at `ui://designesy/report-app`. Apps-capable hosts
//      (Claude Desktop, Cursor v2.6+, VS Code, Goose) fetch this HTML
//      and render it in a sandboxed iframe inside the conversation.
//      The iframe calls back into the host via JSON-RPC over postMessage
//      to re-run reports on new URLs without leaving the chat.
//
//   2. As a standalone URL in any browser:
//      `https://www.designesy.org/api/report/app?url=...` opens the
//      dashboard directly. No host required. The MCP tool also returns
//      this URL as a fallback link for clients that don't support Apps.
//
// The HTML is generated by the shared lib/report-app-html.ts function so
// both this HTTP route and the MCP ui:// resource callback (in /api/mcp)
// serve identical content without a self-fetch round-trip.
//
// CSP-safe (only inline script + style, connect to self). Dark-mode
// native (matches designesy.org); auto-adapts to host theme via
// prefers-color-scheme since the iframe inherits the host OS theme.

import { NextResponse } from 'next/server';
import { buildReportAppHtml } from '../../../lib/report-app-html';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const BASE_URL = 'https://www.designesy.org';

export async function GET(request: Request) {
  const url = new URL(request.url);
  const targetUrl = url.searchParams.get('url') || '';

  const html = buildReportAppHtml(targetUrl, BASE_URL);

  return new NextResponse(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; profile=mcp-app; charset=utf-8',
      'Cache-Control': 'no-store',
      'X-Content-Type-Options': 'nosniff',
      'Referrer-Policy': 'no-referrer',
    },
  });
}