/**
 * Open design intelligence — human + machine catalog of portable Designesy cargo.
 * Single source for /open and /open.json.
 */

export const openIndex = {
  id: 'designesy.open',
  version: '0.1',
  status: 'public' as const,
  name: 'Open design intelligence',
  lede: 'Designesy publishes portable design judgment — contracts, kits, labs, and field checks people and agents can fetch, run, and remix.',
  path: '/open',
  public_url: 'https://www.designesy.org/open',
  machine_url: 'https://www.designesy.org/open.json',
  updated: '2026-07-12',
  thesis:
    'Open design intelligence means rules, prompts, and verification travel with the work — not locked in private taste or closed tools.',
  standing_rules: [
    'Human page and machine export stay synchronized',
    'Every package names purpose, version, and verification path',
    'Silence is not adoption — contract material changes by explicit version',
    'Agents get read-only handoffs by default; edit scope must be explicit',
    'No monogram letter logo; kind language: contract square, lab circle, kit soft square',
    'Public surfaces never display internal control-plane naming',
  ],
  how_to_use: [
    {
      title: 'People',
      meta: 'Start at /open, open a package, apply the rules, leave a field check when useful',
    },
    {
      title: 'Agents',
      meta: 'Fetch open.json, then the package machine URL, then run the kit prompt against an artifact',
    },
    {
      title: 'Builders',
      meta: 'Cite a contract token or name an open tension before shipping new public UI',
    },
  ],
  packages: [
    {
      id: 'designesy.design-system',
      kind: 'contract' as const,
      number: null,
      title: 'Design system',
      version: '0.1.1',
      status: 'public',
      lede: 'Portable design judgment for designesy.org — tokens, motion, components, and adopted Poise interaction rules.',
      human_url: 'https://www.designesy.org/contracts/design-system',
      machine_url: 'https://www.designesy.org/contracts/design-system.json',
      path: '/contracts/design-system',
      machine_path: '/contracts/design-system.json',
    },
    {
      id: 'design-review',
      kind: 'kit' as const,
      number: 'One',
      title: 'Design Review',
      version: '0.1',
      status: 'live',
      lede: 'Turn taste into inspection. Eight dimensions, portable agent prompt, output format, and verification.',
      human_url: 'https://www.designesy.org/kits/design-review',
      machine_url: 'https://www.designesy.org/kits/design-review.json',
      path: '/kits/design-review',
      machine_path: '/kits/design-review.json',
    },
    {
      id: 'poise',
      kind: 'lab' as const,
      number: 'One',
      title: 'Poise',
      version: '0.1',
      status: 'live',
      lede: 'Restrained interaction — wordmark breath, press settle, sound preference, reduced motion. Rules adopted into contract v0.1.1.',
      human_url: 'https://www.designesy.org/labs/poise',
      machine_url: null,
      path: '/labs/poise',
      machine_path: null,
    },
    {
      id: 'review.poise',
      kind: 'review' as const,
      number: null,
      title: 'Field check · Poise',
      version: '0.1',
      status: 'public',
      lede: 'Lab One reviewed with Use Kit One · Design Review. Pass with notes. Evidence for contract adoption.',
      human_url: 'https://www.designesy.org/review/poise',
      machine_url: null,
      path: '/review/poise',
      machine_path: null,
    },
    {
      id: 'review.poise.keyboard',
      kind: 'review' as const,
      number: null,
      title: 'Keyboard path · Poise',
      version: '0.1',
      status: 'public',
      lede: 'Published tab order and focus-visible proof for Lab One.',
      human_url: 'https://www.designesy.org/review/poise/keyboard',
      machine_url: null,
      path: '/review/poise/keyboard',
      machine_path: null,
    },
    {
      id: 'review.designesy-org',
      kind: 'review' as const,
      number: null,
      title: 'Field check · designesy.org',
      version: '0.1',
      status: 'public',
      lede: 'Public surface review of designesy.org against the design system contract.',
      human_url: 'https://www.designesy.org/review/designesy-org',
      machine_url: null,
      path: '/review/designesy-org',
      machine_path: null,
    },
  ],
  machine_exports: [
    {
      title: 'Open index',
      path: '/open.json',
      url: 'https://www.designesy.org/open.json',
      meta: 'Catalog of all portable packages',
    },
    {
      title: 'Design system contract',
      path: '/contracts/design-system.json',
      url: 'https://www.designesy.org/contracts/design-system.json',
      meta: 'v0.1.1 tokens, interaction, verification',
    },
    {
      title: 'Design Review kit',
      path: '/kits/design-review.json',
      url: 'https://www.designesy.org/kits/design-review.json',
      meta: 'Kit One prompt, dimensions, output format',
    },
  ],
  anti_patterns: [
    'Publishing essays without a runnable package',
    'Machine URLs that lag the human page',
    'Claiming openness while rules stay private',
    'Agent prompts without permission boundaries',
    'Versionless rules that change silently',
  ],
  handoff_line:
    'Start open design intelligence at designesy.org/open — human index and machine feed.',
} as const;

export type OpenIndex = typeof openIndex;
