// GENERATED by scripts/build_open_audio.py - do not edit by hand.
// Spoken abstracts for /open package rows: static Opus, one voice.

export interface OpenAudioEntry {
  src: string;
  duration: number;
}

export const OPEN_AUDIO: Record<string, OpenAudioEntry> = {
  "designesy.design-system": { src: "/audio/open/designesy.design-system.opus", duration: 13.87 },
  "design-review": { src: "/audio/open/design-review.opus", duration: 11.02 },
  "poise": { src: "/audio/open/poise.opus", duration: 14.08 },
  "takt": { src: "/audio/open/takt.opus", duration: 17.0 },
  "cadence": { src: "/audio/open/cadence.opus", duration: 20.13 },
  "acoustics": { src: "/audio/open/acoustics.opus", duration: 14.77 },
  "review.poise": { src: "/audio/open/review.poise.opus", duration: 11.5 },
  "review.takt": { src: "/audio/open/review.takt.opus", duration: 17.63 },
  "review.cadence": { src: "/audio/open/review.cadence.opus", duration: 18.43 },
  "review.acoustics": { src: "/audio/open/review.acoustics.opus", duration: 19.26 },
  "review.poise.keyboard": { src: "/audio/open/review.poise.keyboard.opus", duration: 8.1 },
  "review.keyboard": { src: "/audio/open/review.keyboard.opus", duration: 11.75 },
  "open.handoff": { src: "/audio/open/open.handoff.opus", duration: 11.06 },
  "review.designesy-org": { src: "/audio/open/review.designesy-org.opus", duration: 9.96 },
  "acoustic-tokens": { src: "/audio/open/acoustic-tokens.opus", duration: 15.89 },
  "designesy.tokens": { src: "/audio/open/designesy.tokens.opus", duration: 17.56 },
  "designesy.a11y": { src: "/audio/open/designesy.a11y.opus", duration: 17.4 },
  "designesy.motion": { src: "/audio/open/designesy.motion.opus", duration: 19.2 },
  "designesy.maturity": { src: "/audio/open/designesy.maturity.opus", duration: 20.76 },
  "designesy.frameworks": { src: "/audio/open/designesy.frameworks.opus", duration: 16.29 },
  "designesy.changelog": { src: "/audio/open/designesy.changelog.opus", duration: 21.84 },
  "designesy.m3-bridge": { src: "/audio/open/designesy.m3-bridge.opus", duration: 25.5 },
  "designesy.spring-validator": { src: "/audio/open/designesy.spring-validator.opus", duration: 25.04 },
};
