import type { MetadataRoute } from 'next';

const BASE = 'https://www.designesy.org';
const NOW = new Date();

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: BASE,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 1,
    },
    {
      url: `${BASE}/open`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.95,
    },
    {
      url: `${BASE}/open.json`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${BASE}/llms.txt`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE}/llms-full.txt`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE}/.well-known/agent.json`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE}/open/handoff`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE}/docs`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE}/docs/mcp`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${BASE}/score`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.95,
    },
    {
      url: `${BASE}/leaderboard`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE}/score/lovable`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${BASE}/score/v0`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${BASE}/score/bolt`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${BASE}/learn`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${BASE}/learn/what-is-design-verification`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE}/learn/design-verification-vs-linting-vs-visual-regression`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/learn/why-we-built-a-public-design-score`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/privacy`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.55,
    },
    {
      url: `${BASE}/continuity`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE}/labs`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE}/labs/poise`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/labs/takt`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/labs/cadence`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/kits`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE}/kits/design-review`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.9,
    },
    {
      url: `${BASE}/kits/design-review.json`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.65,
    },
    {
      url: `${BASE}/review`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE}/review/poise`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE}/review/takt`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE}/review/cadence`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE}/review/poise/keyboard`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE}/review/keyboard`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/review/designesy-org`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${BASE}/contracts`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.9,
    },
    {
      url: `${BASE}/contracts/design-system`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.85,
    },
    {
      url: `${BASE}/contracts/design-system.json`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${BASE}/contracts/skill`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${BASE}/work`,
      lastModified: NOW,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${BASE}/work/tile`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/work/compile`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/work/continuity`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/work/designesy-org`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE}/work/lovable-dev`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE}/acoustic-tokens`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${BASE}/acoustic-tokens.json`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${BASE}/labs/poise.json`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${BASE}/labs/takt.json`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${BASE}/labs/cadence.json`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${BASE}/graph`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.75,
    },
    {
      url: `${BASE}/graph.json`,
      lastModified: NOW,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
  ];
}
