#!/usr/bin/env python3
"""Generate spoken abstracts for every package in the /open catalog.

Pipeline: fetch canonical open.json -> compose spoken text -> normalize ->
synthesize with a local Piper voice (tuned prosody) -> Opus 32 kbps mono ->
commit assets under apps/site/public/audio/open/ plus a generated TS manifest
(apps/site/lib/open-audio.ts).

Assets are COMMITTED, regenerated only when the catalog changes. CI never
invokes this script (no Piper on Vercel) - determinism comes from hashing
content, exactly like every other receipt on the site.

Usage:
  python apps/site/scripts/build_open_audio.py            # all packages
  python apps/site/scripts/build_open_audio.py poise takt # subset
"""

from __future__ import annotations

import io
import json
import re
import struct
import subprocess
import sys
import urllib.request
import wave
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parent.parent   # apps/site
PUBLIC_AUDIO = SITE_DIR / "public" / "audio" / "open"
LIB_DIR = SITE_DIR / "app" / "lib"
FFMPEG = r"C:\ffmpeg-2025-12-18-git-78c75d546a-essentials_build\bin\ffmpeg.exe"
PIPER_APP = Path.home() / "AppData" / "Local" / "ReadAloudTTS"
VOICES_DIR = PIPER_APP / "voices"

OPEN_JSON_URL = "https://www.designesy.org/open.json"

# Prosody: tuned naturality values (see read-aloud-tts-windows v0.8.1).
LENGTH_SCALE = 1.15
NOISE_SCALE = 0.4
NOISE_W = 0.3
SENTENCE_SILENCE = 0.35

VOICE_ID = "en_US-lessac-medium"

UNICODE_MAP = str.maketrans({
    "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
    "\u2013": "-", "\u2014": ", ", "\u2026": "...", "\u00a0": " ",
    "\u00b7": ", ",   # middle dot separators in titles/ledes -> pause
})

NUM_WORDS = {"0": "zero", "1": "one", "2": "two", "3": "three", "4": "four",
             "5": "five", "6": "six", "7": "seven", "8": "eight", "9": "nine"}

KIND_PHRASE = {
    "contract": "Contract",
    "kit": "Use kit",
    "lab": "Lab",
    "review": "Field check",
    "tool": "Tool",
}


def load_catalog() -> list[dict]:
    cache = SITE_DIR / "scripts" / "open.json.cache"
    if cache.exists():
        raw = cache.read_text(encoding="utf-8")
    else:
        req = urllib.request.Request(OPEN_JSON_URL, headers={"User-Agent": "designesy-build"})
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
        cache.write_text(raw, encoding="utf-8")
    return json.loads(raw)["packages"]


def spoken_version(v: str) -> str:
    nums = re.findall(r"\d+", v)
    if not nums:
        return ""
    parts = ["".join(NUM_WORDS[c] for c in n) for n in nums]
    return "version " + " point ".join(parts)


def compose_spoken(pkg: dict) -> str:
    title = pkg.get("title", pkg["id"])
    kind = KIND_PHRASE.get(pkg.get("kind", ""), pkg.get("kind", "").capitalize())
    head = f"{title}. {kind}"
    ver = pkg.get("version", "")
    if ver:
        head += f", {spoken_version(ver)}"
    text = f"{head}. {pkg.get('lede', '').strip()}"
    text = text.translate(UNICODE_MAP)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def synth_wav(text: str, out_wav: Path) -> float:
    from piper import PiperVoice, SynthesisConfig
    model = VOICES_DIR / f"{VOICE_ID}.onnx"
    cfg = VOICES_DIR / f"{VOICE_ID}.onnx.json"
    voice = PiperVoice.load(str(model), config_path=str(cfg))
    syn_cfg = SynthesisConfig(
        length_scale=LENGTH_SCALE,
        noise_scale=NOISE_SCALE,
        noise_w_scale=NOISE_W,
    )
    chunks = list(voice.synthesize(text, syn_cfg))
    sr = chunks[0].sample_rate
    pcm = io.BytesIO()
    total = 0
    for i, c in enumerate(chunks):
        if i > 0:
            n = int(sr * SENTENCE_SILENCE)
            pcm.write(struct.pack(f"<{n}h", *([0] * n)))
            total += n
        b = c.audio_int16_bytes
        pcm.write(b)
        total += len(b) // 2
    with wave.open(str(out_wav), "wb") as w:
        w.setframerate(sr)
        w.setsampwidth(2)
        w.setnchannels(1)
        w.writeframes(pcm.getvalue())
    return total / sr


def wav_to_opus(wav: Path, opus: Path) -> None:
    subprocess.run(
        [FFMPEG, "-y", "-loglevel", "error", "-i", str(wav),
         "-c:a", "libopus", "-b:a", "32k", "-ac", "1", str(opus)],
        check=True,
    )


def ts_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def write_manifest(entries: list[dict]) -> None:
    lines = [
        "// GENERATED by scripts/build_open_audio.py - do not edit by hand.",
        "// Spoken abstracts for /open package rows: static Opus, one voice.",
        "",
        "export interface OpenAudioEntry {",
        "  src: string;",
        "  duration: number;",
        "}",
        "",
        "export const OPEN_AUDIO: Record<string, OpenAudioEntry> = {",
    ]
    for e in entries:
        lines.append(
            f"  {ts_string(e['id'])}: "
            f"{{ src: {ts_string(e['src'])}, duration: {e['duration']} }},"
        )
    lines.append("};")
    out = LIB_DIR / "open-audio.ts"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    only = set(sys.argv[1:])
    PUBLIC_AUDIO.mkdir(parents=True, exist_ok=True)
    entries: list[dict] = []
    for pkg in load_catalog():
        pid = pkg["id"]
        if only and pid not in only:
            continue
        text = compose_spoken(pkg)
        wav = PUBLIC_AUDIO / f"{pid}.wav"
        opus = PUBLIC_AUDIO / f"{pid}.opus"
        dur = synth_wav(text, wav)
        wav_to_opus(wav, opus)
        wav.unlink()
        entries.append({"id": pid, "src": f"/audio/open/{pid}.opus",
                        "duration": round(dur, 2)})
        print(f"ok {pid} {dur:.1f}s")
    write_manifest(entries)
    total_kb = sum((PUBLIC_AUDIO / f"{e['id']}.opus").stat().st_size
                   for e in entries) // 1024
    print(f"\n{len(entries)} abstracts, {total_kb} KB opus total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
